### ISSUE TITLE
February 04, 2020 | Code-Review : The Poodles

### ISSUE THREAD

**Issue by jabichris** [Meltrust/NYtimes-clone#1]
Nice work, It is a good practice to put all CSS files in one folder. I hope you will take this into consideration as you keep on working on this project.

**Comment by Flakster** [comment]
So far so good @Meltrust. Remember to use the margin shorthand, specially when you want to center boxes by  simply margin: 0 auto; 

https://github.com/Meltrust/NYtimes-clone/blob/4188cd49babebe06d626d2a34ef91a694787bb99/main.css#L184-L185

Happy coding!
